### ISSUE TITLE
Chrome extension: activate via shortcut

### ISSUE THREAD

**Issue by Donaldini** [mrmrs/pesticide#30]
It would be awesome if there was a shortcut to (de)activate the extension in Chrome.

Sometimes I want to toggle between off and on to check changes.

**Comment by bluetidepro** [comment]
I think this can be done without having to modify the plugin at all. Check this out @Donaldini: http://lifehacker.com/add-custom-keyboard-shortcuts-to-chrome-extensions-for-1595322121 - Does that solve your problem?

**Comment by Donaldini** [comment]
Wow, even better! An instant solution :-)

Thanks @bluetidepro :+1:
