### ISSUE TITLE
Safari extension no more available

### ISSUE THREAD

**Issue by MonsieurNayaki** [mrmrs/pesticide#35]
Just like the title say
Wanted to download the Safari extension, seem like link broken/removed from Safari extensions market.
Can you post the extension directly on the github repo ? 

Thanks

**Comment by paulmolluzzo** [comment]
Direct download link: http://pesticide.molluzzo.com/pesticide_for_safari.safariextz

**Comment by LasseRafn** [comment]
Does not work sadly
