### ISSUE TITLE
pesticide.css is not valid CSS

### ISSUE THREAD

**Issue by tbassetto** [mrmrs/pesticide#37]
Or am I missing something?

https://github.com/mrmrs/pesticide/blob/ac7058c5b354fdf1e0b87b91172b7264dccdf751/css/pesticide.css

**Comment by enociz** [comment]
I see what you mean.

I suggest that @mrmrs fix this ASAP so, +1

**Comment by mrmrs** [comment]
@tbassetto Looks like an error with what gulp was outputting. An easy fix. The minified version is still good to go.

**Comment by mrmrs** [comment]
@enociz - as this is an open source project and I am a human that has a life and a job - it's a bit deflating to receive suggestions that this is fixed ASAP to be honest. I'd welcome a pull request if this is urgent for you. I have ~300 open source projects. There is lots of work to do - but none of it is urgent and none of it is ASAP. It's not a hospital. No one is going to die :)

**Comment by enociz** [comment]
@mrmrs - Sorry man, I totally understand your situation. I should have worded it better. Sorry for that.

**Comment by mrmrs** [comment]
This is fixed.
