### ISSUE TITLE
Different versions for css and sass?

### ISSUE THREAD

**Issue by exalted** [mrmrs/pesticide#39]
Hi,

I see [css version](https://github.com/mrmrs/pesticide/blob/b8e27b5c308bf94fac1e6bd968df82c0c74468e2/css/pesticide.css) and [sass version](https://github.com/mrmrs/pesticide/blob/b8e27b5c308bf94fac1e6bd968df82c0c74468e2/sass/pesticide.scss) read different version numbers (i.e., `v1.3.0` and `v0.1.0`).

Is there any reason why those are different please?

Thanks.

**Comment by mrmrs** [comment]
@exalted probably just an error on my part as those are manually updated. Thanks for the heads up.

**Comment by exalted** [comment]
:+1:
