### ISSUE TITLE
Request: Opera Extension

### ISSUE THREAD

**Issue by coliff** [mrmrs/pesticide#41]
Hi. I love the Pesticide Chrome extension, but I often use Opera browser and miss Pesticide there. Any plans to make an Opera extension?

**Comment by enociz** [comment]
I don't know if anyone has plans but I think that a better thing would be to have a bookmarklet meaning that it could be used in almost any browser.

**Comment by mrmrs** [comment]
I believe there is already a bookmarklet

https://github.com/mrmrs/pesticide/blob/master/js/pesticide.min.js
