### ISSUE TITLE
Similar idea to this :)

### ISSUE THREAD

**Issue by co0kie** [mrmrs/pesticide#50]
I also have the same concept about a year ago, only you run it manually in your console. It's a small javascript snippet code and I use box-shadow instead of outline. here http://codepen.io/co0kie/pen/wazBGx . Your chrome extension is very helpful for us devs. :)

**Comment by rafaelrinaldi** [comment]
Hey @co0kie this is really cool too! `box-shadow` is also a good idea. We went with `outline` just because it was the simplest option to draw a box without affecting layout.

We're glad the Chrome extension is helpful 👍 

Cheers.
